### ISSUE TITLE
Invalid cell value Error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [andreabalducci/excellibrary#132]
```
Exception Details:
System.Exception was caught
  HResult=-2146233088
  Message=Invalid cell value.
  Source=ExcelLibrary
  StackTrace:
       at ExcelLibrary.BinaryFileFormat.WorkSheetEncoder.EncodeCell(Cell cell, SharedResource sharedResource)
       at ExcelLibrary.BinaryFileFormat.WorkSheetEncoder.Encode(Worksheet worksheet, SharedResource sharedResource)
       at ExcelLibrary.BinaryFileFormat.WorkbookEncoder.EncodeWorkbook(Workbook workbook)
       at ExcelLibrary.BinaryFileFormat.WorkbookEncoder.Encode(Workbook workbook, Stream stream)
       at ExcelLibrary.SpreadSheet.Workbook.Save(String file)
       at ExcelLibrary.DataSetHelper.CreateWorkbook(String filePath, DataSet dataset)
       at MAX.MaxForms.SOF.DataSearchPrint.SaveToExcel(DataSet ds, String filename) in D:\MAX\Project\MAX\MaxForms\SOF\DataSearchPrint.cs:line 770
  InnerException: 



What version of the product are you using? On what operating system?
-> ExcelLibrary_20110730.zip/ExcelLibrary.dll
-> OS: win 8 release preview & xp both have same error.
-> Visual studio 2010
-> DotNet Framework 4.0

Please provide any additional information below.
 Data is in japanese and unintelligible characters were being printed earlier. So i tried the latest version and now, it doesnt generate the excel file at all.

 Does it support Japanese & Chinese characters? Or should the encoding be changed to UTF-16?

 How about setting a default font that supports unicode charactes in cell formatting?

```

Original issue reported on code.google.com by `princekt...@gmail.com` on 13 Jun 2012 at 2:10

**Comment by GoogleCodeExporter** [comment]
```
if the dataset has a null value, when creating the file this error is thrown
```

Original comment by `ganeshba...@gmail.com` on 5 Jul 2012 at 11:58

**Comment by GoogleCodeExporter** [comment]
```
Where I can found latest dll with the fix of this issue ?
```

Original comment by `deepjyot...@gmail.com` on 12 Jul 2012 at 2:26

**Comment by GoogleCodeExporter** [comment]
```
This issue ocurrs if the dataset has an item with a DBNull value or a Guid 
value. Look for the attached dataset.
```

Original comment by `gusa...@gmail.com` on 6 Dec 2012 at 2:30

Attachments:
- [dataset.xml](https://storage.googleapis.com/google-code-attachments/excellibrary/issue-132/comment-3/dataset.xml)

**Comment by GoogleCodeExporter** [comment]
```
I also received this error when the dataset has an item with an Int64. I am 
just converting ToString()
```

Original comment by `CurlyHai...@gmail.com` on 29 Aug 2013 at 3:15
