### ISSUE TITLE
Couldn't load file or assembly

### ISSUE THREAD

**Issue by GoogleCodeExporter** [andreabalducci/excellibrary#87]
```
I got the error below when I run the exe file of my project using excellibrary. 
How can I resolve this problem?

1.See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'ExcelLibrary, 
Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its 
dependencies. The system cannot find the file specified.
File name: 'ExcelLibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at UpDown.Form1.button1_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value 
[HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure 
logging.
To turn this feature off, remove the registry value 
[HKLM\Software\Microsoft\Fusion!EnableLog].


2.
3.

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?


Please provide any additional information below.

```

Original issue reported on code.google.com by `aliercan...@gmail.com` on 25 Apr 2011 at 7:41

**Comment by GoogleCodeExporter** [comment]
```

> expected output windows form application to get all users in excel
> Did the code on visual studio with .net frame work 2.0 and added excel 
library version 1.0.0.0 , operating system windows server 2003

```

Original comment by `manu.red...@gmail.com` on 7 Jan 2015 at 2:53
