### ISSUE TITLE
Exception of type 'System.OutOfMemoryException' was thrown.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [andreabalducci/excellibrary#95]
```
What steps will reproduce the problem?
1.Just tried to open a .xls like this
 ExcelLibrary.SpreadSheet.Workbook book = ExcelLibrary.SpreadSheet.Workbook.Load("stringfilename");

What is the expected output? What do you see instead?
Expect to read the excel. But exception thrown

What version of the product are you using? On what operating system?
April 14 version (14042011)

```

Original issue reported on code.google.com by `joethoma...@gmail.com` on 16 Jun 2011 at 11:03

**Comment by GoogleCodeExporter** [comment]
```
The same to you...
```

Original comment by `peng1...@gmail.com` on 22 Jul 2011 at 5:11

**Comment by GoogleCodeExporter** [comment]
```
for .xsl file it worked ... but when i try to load .xslm its throwing me this 
exception . Please if some one can help it will be real good
```

Original comment by `kunal...@gmail.com` on 20 Aug 2011 at 11:52

**Comment by GoogleCodeExporter** [comment]
```
I too have this issue.  It happens with xlsx files, but not with xls files.  I 
have tried handing the constructor a stream as well as the file name with the 
same result.  

My spread sheet has 6 pages, and around 800 rows per page.  

There is no inner exception.  Here is the stack trace from the exception.

   at System.Collections.Generic.List`1..ctor(Int32 capacity)
   at ExcelLibrary.CompoundDocumentFormat.MasterSectorAllocation.InitializeMasterSectorAllocationTable()
   at ExcelLibrary.CompoundDocumentFormat.MasterSectorAllocation..ctor(CompoundDocument document)
   at ExcelLibrary.CompoundDocumentFormat.CompoundDocument..ctor(Stream stream, FileHeader header)
   at ExcelLibrary.CompoundDocumentFormat.CompoundDocument.Open(Stream stream)
   at ExcelLibrary.CompoundDocumentFormat.CompoundDocument.Load(Stream stream)
   at ExcelLibrary.SpreadSheet.Workbook.Load(Stream stream)
   at test.cs.Program.AssociateProgramBook() in C:\Users\tmckenzie\documents\visual studio 2010\Projects\SMDB\test.cs\Program.cs:line 24
   at test.cs.Program.Main(String[] args) in C:\Users\tmckenzie\documents\visual studio 2010\Projects\SMDB\test.cs\Program.cs:line 18
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

Original comment by `TimMcken...@gmail.com` on 21 Aug 2011 at 8:20

**Comment by GoogleCodeExporter** [comment]
```
Same exact problem here as in Comment 3, but i have an xlsx file with 2 empty 
sheets and 1 sheet with 10 cells filled with data.

```

Original comment by `roner...@gmail.com` on 9 Sep 2012 at 7:03

**Comment by GoogleCodeExporter** [comment]
```
Sorry to post here, but I'm with the same problem with xlsx EXCEL files. I 
can't to use interop or ole db connection library's to read and write my 
sheets. I not get to resolve it.
```

Original comment by `rodrigo.torresleme` on 3 Jun 2013 at 12:31

**Comment by GoogleCodeExporter** [comment]
```
Any news on this? I have the same problem.
```

Original comment by `nimisnic...@gmail.com` on 1 Jul 2013 at 2:06

**Comment by GoogleCodeExporter** [comment]
```
I get the same error when I try to call the Save method on a workbook that I 
have populated in code. Any solutions yet?
```

Original comment by `007mshar...@gmail.com` on 29 Jul 2013 at 10:38

**Comment by GoogleCodeExporter** [comment]
```
I have the same problem.
```

Original comment by `sahe...@gmail.com` on 27 Sep 2013 at 8:29

**Comment by GoogleCodeExporter** [comment]
```
I've got the same problem too, while opening an XLSX using the "stream" 
constructor of Workbook.Load
```

Original comment by `rgoen...@gmail.com` on 24 Oct 2013 at 4:20

**Comment by GoogleCodeExporter** [comment]
```
Dim book = ExcelLibrary.SpreadSheet.Workbook.Load(fileName or Stream)

Exception of type 'System.OutOfMemoryException' was thrown.


```

Original comment by `an...@avmsistemas.net` on 7 Jan 2015 at 8:45
